### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by kft334** [XmYx/ainodes-engine#4]
Looking forward to trying this but I'm getting the following error:

Already up to date.
Using HF Cache in app dir
Traceback (most recent call last):
  File "D:\ainodes-engine\main.py", line 35, in <module>
    from ainodes_frontend.nodes.base.node_window import CalculatorWindow
  File "D:\ainodes-engine\ainodes_frontend\nodes\base\node_window.py", line 8, in <module>
    from ainodes_frontend.nodes.base.node_sub_window import CalculatorSubWindow
  File "D:\ainodes-engine\ainodes_frontend\nodes\base\node_sub_window.py", line 8, in <module>
    from ainodes_frontend.nodes.base.node_config import CALC_NODES, get_class_from_opcode, LISTBOX_MIMETYPE, node_categories
  File "D:\ainodes-engine\ainodes_frontend\nodes\base\node_config.py", line 77, in <module>
    from ainodes_frontend.nodes.image_nodes import image_op_node, input, output, video_input, video_save_node, image_blend_node, matte_node
  File "D:\ainodes-engine\ainodes_frontend\nodes\image_nodes\matte_node.py", line 12, in <module>
    from ainodes_backend.matte.matte import MatteInference
  File "D:\ainodes-engine\ainodes_backend\matte\matte.py", line 13, in <module>
    result = subprocess.run(['wget', '--version'], capture_output=True, check=True)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

And I don't know if it's planned but it would be great to be able to use this as an API in the future.

**Comment by XmYx** [comment]
Did you start the app with the launcher.py or run.bat?

**Comment by kft334** [comment]
run.bat on Win 10. I also tried launcher.py and main.py with the same error.

**Comment by XmYx** [comment]
it suggests that wget is not working in windows, one second, I'll add a try except and print there!

**Comment by XmYx** [comment]
This one is likely solved now, please test, but now It is downloading Matting the model without wget.
